/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionType = IDL.Variant({
  'fee' : IDL.Null,
  'donation' : IDL.Null,
  'payment' : IDL.Null,
  'refund' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BroadcastPriority = IDL.Variant({
  'normal' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
});
export const Role = IDL.Variant({ 'member' : IDL.Null, 'admin' : IDL.Null });
export const Broadcast = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : IDL.Text,
  'createdAt' : IDL.Int,
  'priority' : BroadcastPriority,
});
export const DM = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'sentAt' : IDL.Int,
  'toMemberId' : IDL.Text,
  'fromMemberId' : IDL.Text,
});
export const FacilityStatus = IDL.Variant({
  'available' : IDL.Null,
  'maintenance' : IDL.Null,
  'inUse' : IDL.Null,
});
export const Facility = IDL.Record({
  'id' : IDL.Text,
  'status' : FacilityStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'suspended' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
  'role' : Role,
  'email' : IDL.Text,
  'idCardImage' : IDL.Opt(IDL.Text),
});
export const Policy = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'category' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'memberId' : IDL.Text,
  'createdAt' : IDL.Int,
  'type' : TransactionType,
  'description' : IDL.Text,
  'facilityId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'memberId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const SessionData = IDL.Record({
  'memberId' : IDL.Opt(IDL.Text),
  'sessionType' : IDL.Text,
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFacility' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPolicy' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addTransaction' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Int,
        IDL.Text,
        TransactionType,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBroadcast' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, BroadcastPriority],
      [],
      [],
    ),
  'createMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Principal],
      [],
      [],
    ),
  'createSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'deactivatePolicy' : IDL.Func([IDL.Text], [], []),
  'deleteMember' : IDL.Func([IDL.Text], [], []),
  'deletePolicy' : IDL.Func([IDL.Text], [], []),
  'destroySession' : IDL.Func([IDL.Text], [], []),
  'getAboutText' : IDL.Func([], [IDL.Text], ['query']),
  'getAllBroadcasts' : IDL.Func([], [IDL.Vec(Broadcast)], ['query']),
  'getAllDMs' : IDL.Func([], [IDL.Vec(DM)], ['query']),
  'getAllFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getAllPolicies' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getBroadcast' : IDL.Func([IDL.Text], [Broadcast], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactEmail' : IDL.Func([], [IDL.Text], ['query']),
  'getDM' : IDL.Func([IDL.Text], [DM], ['query']),
  'getFacility' : IDL.Func([IDL.Text], [Facility], ['query']),
  'getFeaturesList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMember' : IDL.Func([IDL.Text], [Member], ['query']),
  'getMemberByQrId' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
  'getPasswords' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
  'getPolicy' : IDL.Func([IDL.Text], [Policy], ['query']),
  'getTransaction' : IDL.Func([IDL.Text], [Transaction], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loadTmpFS' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
  'markDMAsRead' : IDL.Func([IDL.Text], [], []),
  'removeFacility' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTmpFS' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'sendDM' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setContactEmail' : IDL.Func([IDL.Text], [], []),
  'setMemberIdCard' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setPasswords' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateAboutText' : IDL.Func([IDL.Text], [], []),
  'updateFacilityStatus' : IDL.Func([IDL.Text, FacilityStatus], [], []),
  'updateFeaturesList' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Role], [], []),
  'updatePolicy' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(SessionData)], ['query']),
  'verifyPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionType = IDL.Variant({
    'fee' : IDL.Null,
    'donation' : IDL.Null,
    'payment' : IDL.Null,
    'refund' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BroadcastPriority = IDL.Variant({
    'normal' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
  });
  const Role = IDL.Variant({ 'member' : IDL.Null, 'admin' : IDL.Null });
  const Broadcast = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : IDL.Text,
    'createdAt' : IDL.Int,
    'priority' : BroadcastPriority,
  });
  const DM = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'sentAt' : IDL.Int,
    'toMemberId' : IDL.Text,
    'fromMemberId' : IDL.Text,
  });
  const FacilityStatus = IDL.Variant({
    'available' : IDL.Null,
    'maintenance' : IDL.Null,
    'inUse' : IDL.Null,
  });
  const Facility = IDL.Record({
    'id' : IDL.Text,
    'status' : FacilityStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'joinedAt' : IDL.Int,
    'role' : Role,
    'email' : IDL.Text,
    'idCardImage' : IDL.Opt(IDL.Text),
  });
  const Policy = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'category' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'memberId' : IDL.Text,
    'createdAt' : IDL.Int,
    'type' : TransactionType,
    'description' : IDL.Text,
    'facilityId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'memberId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const SessionData = IDL.Record({
    'memberId' : IDL.Opt(IDL.Text),
    'sessionType' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFacility' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPolicy' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addTransaction' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Int,
          IDL.Text,
          TransactionType,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBroadcast' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, BroadcastPriority],
        [],
        [],
      ),
    'createMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Principal],
        [],
        [],
      ),
    'createSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'deactivatePolicy' : IDL.Func([IDL.Text], [], []),
    'deleteMember' : IDL.Func([IDL.Text], [], []),
    'deletePolicy' : IDL.Func([IDL.Text], [], []),
    'destroySession' : IDL.Func([IDL.Text], [], []),
    'getAboutText' : IDL.Func([], [IDL.Text], ['query']),
    'getAllBroadcasts' : IDL.Func([], [IDL.Vec(Broadcast)], ['query']),
    'getAllDMs' : IDL.Func([], [IDL.Vec(DM)], ['query']),
    'getAllFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getAllPolicies' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getBroadcast' : IDL.Func([IDL.Text], [Broadcast], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactEmail' : IDL.Func([], [IDL.Text], ['query']),
    'getDM' : IDL.Func([IDL.Text], [DM], ['query']),
    'getFacility' : IDL.Func([IDL.Text], [Facility], ['query']),
    'getFeaturesList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMember' : IDL.Func([IDL.Text], [Member], ['query']),
    'getMemberByQrId' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
    'getPasswords' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
    'getPolicy' : IDL.Func([IDL.Text], [Policy], ['query']),
    'getTransaction' : IDL.Func([IDL.Text], [Transaction], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loadTmpFS' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
    'markDMAsRead' : IDL.Func([IDL.Text], [], []),
    'removeFacility' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTmpFS' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'sendDM' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setContactEmail' : IDL.Func([IDL.Text], [], []),
    'setMemberIdCard' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setPasswords' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateAboutText' : IDL.Func([IDL.Text], [], []),
    'updateFacilityStatus' : IDL.Func([IDL.Text, FacilityStatus], [], []),
    'updateFeaturesList' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Role], [], []),
    'updatePolicy' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(SessionData)], ['query']),
    'verifyPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };