/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Broadcast {
  'id' : string,
  'title' : string,
  'content' : string,
  'authorId' : string,
  'createdAt' : bigint,
  'priority' : BroadcastPriority,
}
export type BroadcastPriority = { 'normal' : null } |
  { 'high' : null } |
  { 'urgent' : null };
export interface DM {
  'id' : string,
  'content' : string,
  'read' : boolean,
  'sentAt' : bigint,
  'toMemberId' : string,
  'fromMemberId' : string,
}
export interface Facility {
  'id' : string,
  'status' : FacilityStatus,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'location' : string,
}
export type FacilityStatus = { 'available' : null } |
  { 'maintenance' : null } |
  { 'inUse' : null };
export interface Member {
  'id' : string,
  'status' : Status,
  'principal' : Principal,
  'name' : string,
  'joinedAt' : bigint,
  'role' : Role,
  'email' : string,
  'idCardImage' : [] | [string],
}
export interface Policy {
  'id' : string,
  'title' : string,
  'active' : boolean,
  'content' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'category' : string,
}
export type Role = { 'member' : null } |
  { 'admin' : null };
export interface SessionData {
  'memberId' : [] | [string],
  'sessionType' : string,
  'createdAt' : bigint,
}
export type Status = { 'active' : null } |
  { 'inactive' : null } |
  { 'suspended' : null };
export interface Transaction {
  'id' : string,
  'memberId' : string,
  'createdAt' : bigint,
  'type' : TransactionType,
  'description' : string,
  'facilityId' : [] | [string],
  'amount' : bigint,
}
export type TransactionType = { 'fee' : null } |
  { 'donation' : null } |
  { 'payment' : null } |
  { 'refund' : null };
export interface UserProfile { 'memberId' : [] | [string], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFacility' : ActorMethod<[string, string, string, string], undefined>,
  'addPolicy' : ActorMethod<[string, string, string, string], undefined>,
  'addTransaction' : ActorMethod<
    [string, string, [] | [string], bigint, string, TransactionType],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBroadcast' : ActorMethod<
    [string, string, string, string, BroadcastPriority],
    undefined
  >,
  'createMember' : ActorMethod<
    [string, string, string, Role, Principal],
    undefined
  >,
  'createSession' : ActorMethod<[string, string, [] | [string]], undefined>,
  'deactivatePolicy' : ActorMethod<[string], undefined>,
  'deleteMember' : ActorMethod<[string], undefined>,
  'destroySession' : ActorMethod<[string], undefined>,
  'getAboutText' : ActorMethod<[], string>,
  'getAllBroadcasts' : ActorMethod<[], Array<Broadcast>>,
  'getAllDMs' : ActorMethod<[], Array<DM>>,
  'getAllFacilities' : ActorMethod<[], Array<Facility>>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getAllPolicies' : ActorMethod<[], Array<Policy>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBroadcast' : ActorMethod<[string], Broadcast>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDM' : ActorMethod<[string], DM>,
  'getFacility' : ActorMethod<[string], Facility>,
  'getFeaturesList' : ActorMethod<[], Array<string>>,
  'getMember' : ActorMethod<[string], Member>,
  'getMemberByQrId' : ActorMethod<[string], [] | [Member]>,
  'getPasswords' : ActorMethod<[], [string, string]>,
  'getPolicy' : ActorMethod<[string], Policy>,
  'getTransaction' : ActorMethod<[string], Transaction>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markDMAsRead' : ActorMethod<[string], undefined>,
  'removeFacility' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendDM' : ActorMethod<[string, string, string], undefined>,
  'setMemberIdCard' : ActorMethod<[string, string], undefined>,
  'setPasswords' : ActorMethod<[string, string], undefined>,
  'updateAboutText' : ActorMethod<[string], undefined>,
  'updateFacilityStatus' : ActorMethod<[string, FacilityStatus], undefined>,
  'updateFeaturesList' : ActorMethod<[Array<string>], undefined>,
  'updateMember' : ActorMethod<[string, string, string, Role], undefined>,
  'updatePolicy' : ActorMethod<[string, string, string], undefined>,
  'validateSession' : ActorMethod<[string], [] | [SessionData]>,
  'verifyPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];