/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Facility {
    id: string;
    status: FacilityStatus;
    name: string;
    createdAt: bigint;
    description: string;
    location: string;
}
export interface Policy {
    id: string;
    title: string;
    active: boolean;
    content: string;
    createdAt: bigint;
    updatedAt: bigint;
    category: string;
}
export interface Broadcast {
    id: string;
    title: string;
    content: string;
    authorId: string;
    createdAt: bigint;
    priority: BroadcastPriority;
}
export interface Transaction {
    id: string;
    memberId: string;
    createdAt: bigint;
    type: TransactionType;
    description: string;
    facilityId?: string;
    amount: bigint;
}
export interface SessionData {
    memberId?: string;
    sessionType: string;
    createdAt: bigint;
}
export interface DM {
    id: string;
    content: string;
    read: boolean;
    sentAt: bigint;
    toMemberId: string;
    fromMemberId: string;
}
export interface Member {
    id: string;
    status: Status;
    principal: Principal;
    name: string;
    joinedAt: bigint;
    role: Role;
    email: string;
    idCardImage?: string;
}
export interface UserProfile {
    memberId?: string;
    name: string;
}
export enum BroadcastPriority {
    normal = "normal",
    high = "high",
    urgent = "urgent"
}
export enum FacilityStatus {
    available = "available",
    maintenance = "maintenance",
    inUse = "inUse"
}
export enum Role {
    member = "member",
    admin = "admin"
}
export enum Status {
    active = "active",
    inactive = "inactive",
    suspended = "suspended"
}
export enum TransactionType {
    fee = "fee",
    donation = "donation",
    payment = "payment",
    refund = "refund"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFacility(id: string, name: string, description: string, location: string): Promise<void>;
    addPolicy(id: string, title: string, content: string, category: string): Promise<void>;
    addTransaction(id: string, memberId: string, facilityId: string | null, amount: bigint, description: string, type: TransactionType): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBroadcast(id: string, title: string, content: string, authorId: string, priority: BroadcastPriority): Promise<void>;
    createMember(id: string, name: string, email: string, role: Role, principal: Principal): Promise<void>;
    createSession(token: string, sessionType: string, memberId: string | null): Promise<void>;
    deactivatePolicy(id: string): Promise<void>;
    deleteMember(id: string): Promise<void>;
    destroySession(token: string): Promise<void>;
    getAllBroadcasts(): Promise<Array<Broadcast>>;
    getAllDMs(): Promise<Array<DM>>;
    getAllFacilities(): Promise<Array<Facility>>;
    getAllMembers(): Promise<Array<Member>>;
    getAllPolicies(): Promise<Array<Policy>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getBroadcast(id: string): Promise<Broadcast>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDM(id: string): Promise<DM>;
    getFacility(id: string): Promise<Facility>;
    getMember(id: string): Promise<Member>;
    getMemberByQrId(qrId: string): Promise<Member | null>;
    getPasswords(): Promise<[string, string]>;
    getPolicy(id: string): Promise<Policy>;
    getTransaction(id: string): Promise<Transaction>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markDMAsRead(id: string): Promise<void>;
    removeFacility(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendDM(fromMemberId: string, toMemberId: string, content: string): Promise<void>;
    setMemberIdCard(memberId: string, imageDataUrl: string): Promise<void>;
    setPasswords(p1: string, p2: string): Promise<void>;
    updateFacilityStatus(id: string, status: FacilityStatus): Promise<void>;
    updateMember(id: string, name: string, email: string, role: Role): Promise<void>;
    updatePolicy(id: string, title: string, content: string): Promise<void>;
    validateSession(token: string): Promise<SessionData | null>;
    verifyPassword(pw: string): Promise<boolean>;
}
import type { Broadcast as _Broadcast, BroadcastPriority as _BroadcastPriority, Facility as _Facility, FacilityStatus as _FacilityStatus, Member as _Member, Role as _Role, SessionData as _SessionData, Status as _Status, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFacility(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFacility(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFacility(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPolicy(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPolicy(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPolicy(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTransaction(arg0: string, arg1: string, arg2: string | null, arg3: bigint, arg4: string, arg5: TransactionType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_TransactionType_n2(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_TransactionType_n2(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBroadcast(arg0: string, arg1: string, arg2: string, arg3: string, arg4: BroadcastPriority): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBroadcast(arg0, arg1, arg2, arg3, to_candid_BroadcastPriority_n6(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBroadcast(arg0, arg1, arg2, arg3, to_candid_BroadcastPriority_n6(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createMember(arg0: string, arg1: string, arg2: string, arg3: Role, arg4: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMember(arg0, arg1, arg2, to_candid_Role_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMember(arg0, arg1, arg2, to_candid_Role_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async createSession(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deactivatePolicy(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivatePolicy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivatePolicy(arg0);
            return result;
        }
    }
    async deleteMember(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async destroySession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.destroySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.destroySession(arg0);
            return result;
        }
    }
    async getAllBroadcasts(): Promise<Array<Broadcast>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBroadcasts();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBroadcasts();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDMs(): Promise<Array<DM>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDMs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDMs();
            return result;
        }
    }
    async getAllFacilities(): Promise<Array<Facility>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFacilities();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFacilities();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembers(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPolicies(): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPolicies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPolicies();
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBroadcast(arg0: string): Promise<Broadcast> {
        if (this.processError) {
            try {
                const result = await this.actor.getBroadcast(arg0);
                return from_candid_Broadcast_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBroadcast(arg0);
            return from_candid_Broadcast_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDM(arg0: string): Promise<DM> {
        if (this.processError) {
            try {
                const result = await this.actor.getDM(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDM(arg0);
            return result;
        }
    }
    async getFacility(arg0: string): Promise<Facility> {
        if (this.processError) {
            try {
                const result = await this.actor.getFacility(arg0);
                return from_candid_Facility_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFacility(arg0);
            return from_candid_Facility_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMember(arg0: string): Promise<Member> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_Member_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_Member_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberByQrId(arg0: string): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberByQrId(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberByQrId(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPasswords(): Promise<[string, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getPasswords();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPasswords();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getPolicy(arg0: string): Promise<Policy> {
        if (this.processError) {
            try {
                const result = await this.actor.getPolicy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPolicy(arg0);
            return result;
        }
    }
    async getTransaction(arg0: string): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_Transaction_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_Transaction_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markDMAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markDMAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDMAsRead(arg0);
            return result;
        }
    }
    async removeFacility(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFacility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFacility(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendDM(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendDM(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendDM(arg0, arg1, arg2);
            return result;
        }
    }
    async setMemberIdCard(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMemberIdCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMemberIdCard(arg0, arg1);
            return result;
        }
    }
    async setPasswords(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPasswords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPasswords(arg0, arg1);
            return result;
        }
    }
    async updateFacilityStatus(arg0: string, arg1: FacilityStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFacilityStatus(arg0, to_candid_FacilityStatus_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFacilityStatus(arg0, to_candid_FacilityStatus_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMember(arg0: string, arg1: string, arg2: string, arg3: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(arg0, arg1, arg2, to_candid_Role_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(arg0, arg1, arg2, to_candid_Role_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updatePolicy(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePolicy(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePolicy(arg0, arg1, arg2);
            return result;
        }
    }
    async validateSession(arg0: string): Promise<SessionData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPassword(arg0);
            return result;
        }
    }
}
function from_candid_BroadcastPriority_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BroadcastPriority): BroadcastPriority {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Broadcast_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Broadcast): Broadcast {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_FacilityStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FacilityStatus): FacilityStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Facility_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Facility): Facility {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Member_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Member): Member {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SessionData_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionData): SessionData {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Member]): Member | null {
    return value.length === 0 ? null : from_candid_Member_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionData]): SessionData | null {
    return value.length === 0 ? null : from_candid_SessionData_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    authorId: string;
    createdAt: bigint;
    priority: _BroadcastPriority;
}): {
    id: string;
    title: string;
    content: string;
    authorId: string;
    createdAt: bigint;
    priority: BroadcastPriority;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        authorId: value.authorId,
        createdAt: value.createdAt,
        priority: from_candid_BroadcastPriority_n13(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _FacilityStatus;
    name: string;
    createdAt: bigint;
    description: string;
    location: string;
}): {
    id: string;
    status: FacilityStatus;
    name: string;
    createdAt: bigint;
    description: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_FacilityStatus_n18(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        location: value.location
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    principal: Principal;
    name: string;
    joinedAt: bigint;
    role: _Role;
    email: string;
    idCardImage: [] | [string];
}): {
    id: string;
    status: Status;
    principal: Principal;
    name: string;
    joinedAt: bigint;
    role: Role;
    email: string;
    idCardImage?: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n23(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        name: value.name,
        joinedAt: value.joinedAt,
        role: from_candid_Role_n25(_uploadFile, _downloadFile, value.role),
        email: value.email,
        idCardImage: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.idCardImage))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    memberId: string;
    createdAt: bigint;
    type: _TransactionType;
    description: string;
    facilityId: [] | [string];
    amount: bigint;
}): {
    id: string;
    memberId: string;
    createdAt: bigint;
    type: TransactionType;
    description: string;
    facilityId?: string;
    amount: bigint;
} {
    return {
        id: value.id,
        memberId: value.memberId,
        createdAt: value.createdAt,
        type: from_candid_TransactionType_n31(_uploadFile, _downloadFile, value.type),
        description: value.description,
        facilityId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.facilityId)),
        amount: value.amount
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: [] | [string];
    name: string;
}): {
    memberId?: string;
    name: string;
} {
    return {
        memberId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.memberId)),
        name: value.name
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: [] | [string];
    sessionType: string;
    createdAt: bigint;
}): {
    memberId?: string;
    sessionType: string;
    createdAt: bigint;
} {
    return {
        memberId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.memberId)),
        sessionType: value.sessionType,
        createdAt: value.createdAt
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    high: null;
} | {
    urgent: null;
}): BroadcastPriority {
    return "normal" in value ? BroadcastPriority.normal : "high" in value ? BroadcastPriority.high : "urgent" in value ? BroadcastPriority.urgent : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    available: null;
} | {
    maintenance: null;
} | {
    inUse: null;
}): FacilityStatus {
    return "available" in value ? FacilityStatus.available : "maintenance" in value ? FacilityStatus.maintenance : "inUse" in value ? FacilityStatus.inUse : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
} | {
    suspended: null;
}): Status {
    return "active" in value ? Status.active : "inactive" in value ? Status.inactive : "suspended" in value ? Status.suspended : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    admin: null;
}): Role {
    return "member" in value ? Role.member : "admin" in value ? Role.admin : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fee: null;
} | {
    donation: null;
} | {
    payment: null;
} | {
    refund: null;
}): TransactionType {
    return "fee" in value ? TransactionType.fee : "donation" in value ? TransactionType.donation : "payment" in value ? TransactionType.payment : "refund" in value ? TransactionType.refund : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Broadcast>): Array<Broadcast> {
    return value.map((x)=>from_candid_Broadcast_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Facility>): Array<Facility> {
    return value.map((x)=>from_candid_Facility_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Member>): Array<Member> {
    return value.map((x)=>from_candid_Member_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n29(_uploadFile, _downloadFile, x));
}
function to_candid_BroadcastPriority_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BroadcastPriority): _BroadcastPriority {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_FacilityStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FacilityStatus): _FacilityStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId?: string;
    name: string;
}): {
    memberId: [] | [string];
    name: string;
} {
    return {
        memberId: value.memberId ? candid_some(value.memberId) : candid_none(),
        name: value.name
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    fee: null;
} | {
    donation: null;
} | {
    payment: null;
} | {
    refund: null;
} {
    return value == TransactionType.fee ? {
        fee: null
    } : value == TransactionType.donation ? {
        donation: null
    } : value == TransactionType.payment ? {
        payment: null
    } : value == TransactionType.refund ? {
        refund: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FacilityStatus): {
    available: null;
} | {
    maintenance: null;
} | {
    inUse: null;
} {
    return value == FacilityStatus.available ? {
        available: null
    } : value == FacilityStatus.maintenance ? {
        maintenance: null
    } : value == FacilityStatus.inUse ? {
        inUse: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BroadcastPriority): {
    normal: null;
} | {
    high: null;
} | {
    urgent: null;
} {
    return value == BroadcastPriority.normal ? {
        normal: null
    } : value == BroadcastPriority.high ? {
        high: null
    } : value == BroadcastPriority.urgent ? {
        urgent: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    member: null;
} | {
    admin: null;
} {
    return value == Role.member ? {
        member: null
    } : value == Role.admin ? {
        admin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
